In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
import pickle
# pickle is used to save the ML model created by us

In [3]:
df  = pd.read_csv("hiring.csv")
df.shape

(8, 4)

In [7]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [8]:
# experience

df['experience'].fillna(0, inplace=True)

In [9]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [10]:
# test_score

df['test_score'].fillna(df.test_score.mean(), inplace=True)

In [11]:
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

## Dataset is clean now.

In [12]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [13]:
X = df.iloc[:,:-1]
X

experience  test_score  interview_score
0          0    8.000000                9
1          0    8.000000                6
2       five    6.000000                7
3        two   10.000000               10
4      seven    9.000000                6
5      three    7.000000               10
6        ten    7.857143                7
7     eleven    7.000000                8

In [14]:
X.shape

(8, 3)

In [15]:
X.experience.unique()

array([0, 'five', 'two', 'seven', 'three', 'ten', 'eleven'], dtype=object)

In [17]:
# Convert text in the col to integer values

def conv(x):
    dict = {
        'five' : 5,
        'two' : 2,
        'seven' : 7,
        'three' : 3,
        'ten' : 10,
        'eleven' : 11,
        0 : 0
    }
    return dict[x]

In [18]:
X['experience'] = X['experience'].apply(conv)
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [19]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


## X is ready.

In [21]:
y = df.iloc[:,-1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

__I am not going to do traintestsplit as the dataset itself is very small.__

__However, you all are encouraged to do it later as a part of practice and submit it as an assignment.__

__Select any of the ML projects that you have done till now, and deploy it over Flask based on the understanding of today's session.__

In [22]:
# Modeling

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [23]:
# Fit the model
lr.fit(X, y)

LinearRegression()

In [24]:
lr

LinearRegression()

In [25]:
# Prediction on X
y_pred = lr.predict(X)
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [26]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [27]:
from sklearn.metrics import r2_score
r2_score(y_pred, y)

0.9626511210293308

In [28]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [29]:
# Prediction on Unseen Data

lr.predict([[3,9,7]])

array([58315.5019167])

In [30]:
# Prediction on Unseen Data

lr.predict([[10,10,10]])

array([86612.80419155])

In [31]:
# Prediction on Unseen Data

lr.predict([[10,2,3]])

array([55930.47274854])

# Model Deployment

In [32]:
# Here, we will save the 'lr' model to disk as 'model.py'

import pickle
pickle.dump(lr,open('model.pkl','wb'))
# Dump this model by the name 'model.pkl' in the systems HDD/SSD and
# while doing this, write this file using "write bytes" mode

In [33]:
# Lets now try to load the same model by reading it from the
# systems HDD/SSD and use it for prediction

kriti = pickle.load(open("model.pkl","rb"))
kriti

LinearRegression()

In [34]:
lr.predict(X)

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [35]:
kriti.predict(X)

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [37]:
# Prediction on Unseen Data

kriti.predict([[3,9,7]])

array([58315.5019167])

In [39]:
# Prediction on Unseen Data

kriti.predict([[10,10,10]])

array([86612.80419155])

In [41]:
# Prediction on Unseen Data

kriti.predict([[10,2,3]])

array([55930.47274854])

# Happy Learning